spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/user_service
    username: user_service
    password: local_dev
  flyway:
    locations:
      - classpath:db/migration
      - classpath:db/devdata
  data:
    redis:
      host: localhost
      port: 6379
  cloud:
    aws:
      sqs:
        endpoint: http://localhost:4566

app:
  jwt:
    access-token-expiry: 15m
    refresh-token-expiry: 7d
