spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/user_service
    username: user_service
    password: local_dev
  data:
    redis:
      host: redis
  cloud:
    aws:
      sqs:
        endpoint: http://localstack:4566
